### ISSUE TITLE
only show validation error state after blur

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-phone-field#29]
### Expected behavior
The visual error state appears when the phone number input loses focus.

### Actual behavior
The visual error state appears as soon as a validation error is triggered, which will happen as a user is typing.

[AB#1586278](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1586278)

**Comment by Blackbaud-SteveBrush** [comment]
A point of clarification: the form control should be validated on `blur`. The underlying form control should not be marked invalid while the user is typing.

**Comment by Blackbaud-TrevorBurch** [comment]
Closing as #65 is a duplicate and already has a internal work item counterpart
