### ISSUE TITLE
Phone field steals focus

### ISSUE THREAD

**Issue by isaacaggrey** [blackbaud/skyux-phone-field#30]
### Expected behavior

Phone field doesn't steal focus.

### Actual behavior

Phone field steals focus.

### Steps to reproduce

Use a phone field within an inline form repeater. 

Inline form has [logic](https://github.com/blackbaud/skyux-inline-form/blob/3fdc60a823757a4fed09c184aaa43366a57ec0d4/src/app/public/modules/inline-form/inline-form-adapter.service.ts#L25) that will apply focus to the first focusable element, but the phone field steals focus resulting in bad UX for form completion.

### Severity
?

### Impact

All users of the phone field

**Comment by isaacaggrey** [comment]
I would show a Stackblitz but there is no Stackblitz link for phone field.

https://github.com/blackbaud/skyux2-docs/issues/457#issuecomment-557557380

**Comment by Blackbaud-AlexKingman** [comment]
Hey @Blackbaud-IsaacAggrey, we're having some trouble replicating. I've put the phone field inside an inline form with a couple other text input fields. The text input is first. When the inline form opens, the first text field gets focus, as expected. I'm not seeing where the phone field is stealing focus. Am I missing a step?
