### ISSUE TITLE
Allow for keyboard searching of countries in dropdown

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-phone-field#4]
### Expected behavior
In Sky 1 you can start typing a country's name and the dropdown will highlight that entry

### Actual behavior
This does not happen in Sky 2 due to the use of the Sky dropdown component instead of an HTML select field

### Severity
Medium 

### Impact
Causes slowing searching for countries

**Comment by Blackbaud-ToddRoberts** [comment]
Invalidated by new approach in #6
