### ISSUE TITLE
SelectedCountry is not set when Default country is changed/set

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-phone-field#45]
### Expected behavior
When Default country is changed/set, it should then set SelectedCountry to that same country

### Actual behavior
When Default country is changed/set, SelectedCountry doesn't change

**Comment by Blackbaud-DanGrochmal** [comment]
I will contribute a fix shortly.

**Comment by Blackbaud-DanGrochmal** [comment]
https://github.com/blackbaud/skyux-phone-field/pull/46

**Comment by Blackbaud-TrevorBurch** [comment]
Closing in favor of #49
