### ISSUE TITLE
Always return international value format

### ISSUE THREAD

**Issue by Blackbaud-AmandaGlosson** [blackbaud/skyux-phone-field#61]
### Expected behavior
An option exists to always return the international format of a phone number, even for the default country.

### Actual behavior
The default country selected does not return the international phone format. (no +dial_code is returned)

### Steps to reproduce
View the demo phone field at: https://developer.blackbaud.com/skyux/components/phone-field
In the top field enter a US phone number and observe the output does not include the +1 format.
In the second field change the country to US and enter a US phone number. Observe the output does include the +1 format.

### Severity
Medium

### Impact
Usability degraded.
For use cases of legal representative data entry we always want to pass along the international formatted phone number to our vendor for validation and KYC checking. Without this feature I would need to compensate by always setting the default country to US (since i know to always add +1 to those phone numbers) and let the user change the country manually when needed. Alternatively, with this feature - when the form loads, I could set the default country of the phone field to the org's home country, and still get the value output that I need.

[AB#1551359](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1551359)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.2.0`
