### ISSUE TITLE
Validation is checked on keyup when field is pristine

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-phone-field#65]
### Expected behavior

The field should not be marked invalid when the user initially starts typing. Once the user blurs and revisits the field, keyup validation should take place.

### Actual behavior

The field is marked invalid when the user starts typing, when the field is pristine.

[AB#1574926](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1574926)

**Comment by Blackbaud-TrevorBurch** [comment]
In `4.4.1`
