### ISSUE TITLE
Include a disable "country search" option

### ISSUE THREAD

**Issue by Blackbaud-ScottKavanagh** [blackbaud/skyux-phone-field#76]
### Expected behavior
I am hoping that my team can make a contribution.  We would like to have an option that will disable the country search from the phone input control.  This would then only allow numbers for the default country which in our situation would prevent international numbers from being entered. 

### Background
The RE NXT Donation and Event Registration Form teams have encountered failures due to international phone numbers that can't be accepted by the RE Constituent API/RE7 DB.  When this occurs the donation/registration flights will stall requiring manual intervention.  Ideally we'd like to prevent international numbers from being entered by donors/registrants when RE7 hasn't been configured support them. 

[AB#1619746](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1619746)

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ToddRoberts - Thoughts on this? I chatted with Scott and the `supportedCountriesISOs` input may be an option here. However, it did come up that if you only support one country that we do still allow you to enter the country search state. Should we disable the button to trigger the country search if they only support the default country?

**Comment by Blackbaud-ToddRoberts** [comment]
agree that it doesn't make sense to have the country search if only one country is accepted.

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ToddRoberts - should we disable the button or should we hide the flag button altogether?

**Comment by Blackbaud-ToddRoberts** [comment]
i think disable, so that the user can at least see which country it's validating against

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-ScottKavanagh Reach out to Trevor Burch directly if you plan on contributing. Thanks!
